/**
 * File name: Resp
 * Author: Dorsey Q F TANG
 * Date: 5/28/16
 * -----------------------------------------------------
 * Description:
 * -----------------------------------------------------
 */

package com.cloudata.survey.connector.view;

import java.io.Serializable;

/**
 * Declare its subclasses are responses generated by server side.
 *
 * Author: DORSEy
 */
public interface Resp extends Serializable {
}
