/**
 * File name: SurveyResponse
 * Author: Dorsey Q F TANG
 * Date: 5/28/16
 * -----------------------------------------------------
 * Description:
 * -----------------------------------------------------
 */

package com.cloudata.survey.connector.view;

import com.cloudata.survey.connector.LSurveyConstants;
import com.google.gson.annotations.SerializedName;


/**
 * The response that generated by sending survey-related command.
 *
 * Author: DORSEy
 */
public class SurveyResponse implements Resp {
    /**
     * The survey ID.
     */
    @SerializedName(LSurveyConstants.SERIALIZED_RESULT)
    protected int surveyId;

    /**
     * Empty constructor of {@link SurveyResponse}.
     */
    public SurveyResponse() {}

    public int getSurveyId() {
        return surveyId;
    }

    public void setSurveyId(final int surveyId) {
        this.surveyId = surveyId;
    }

    @Override
    public String toString() {
        return "surveyId: " + surveyId;
    }
}
